### ISSUE TITLE
Nested replies: toggle arrow not turning for nested reply

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-comments-changelog#1]
Hi Team, 

First of all, would like to thank you for providing these amazing components! 
Currently, I am implementing them in a Wordpress theme and have found a bug if there is a nested reply. The toggle arrow is not transforming when the details section is toggled. After toggling the main reply the toggle arrow of the nested reply is automatically opened as well. This should stay closed until the nested reply is toggled. Please see below screenshot. 

![image](https://user-images.githubusercontent.com/13256289/77158375-78f8b480-6aa3-11ea-93b8-bd231c9fe526.png)

![image](https://user-images.githubusercontent.com/13256289/77158429-97f74680-6aa3-11ea-9f60-e342f4ef2132.png)

Is this something you can fix?

Regards,
Yannick

**Comment by sebastiano-guerriero** [comment]
Hi Yannick, and thanks for your kind words!

We'll look into this issue asap! We'll update the changelog of this repo as soon as we push an updated version of the component. Cheers.

**Comment by claudia-romano** [comment]
Hi Yannick, 
thanks for the heads-up.
There was an issue with the [Details component](https://codyhouse.co/ds/components/app/details) that is one of the Comments component dependencies. We just pushed a fix for that bug:
https://github.com/CodyHouse/cd-details-changelog/blob/master/changelog.md

Please update the details.scss file and the issue should be fixed. Thanks.

**Comment by YannickMol** [comment]
Hi Claudia, 

Thanks for the reply. Updating the details.scss file has indeed resolved the issue!

Regards,
Yannick
